"""Cube display-name to official Yu-Gi-Oh! name overrides."""

from __future__ import annotations

NAME_MAP = {
    'Burning Abyss - Alich': 'Alich, Malebranche of the Burning Abyss',
    'Burning Abyss - Barbar': 'Barbar, Malebranche of the Burning Abyss',
    'Burning Abyss - Cagna': 'Cagna, Malebranche of the Burning Abyss',
    'Burning Abyss - Calcab': 'Calcab, Malebranche of the Burning Abyss',
    'Burning Abyss - Cir': 'Cir, Malebranche of the Burning Abyss',
    'Burning Abyss - Draghig': 'Draghig, Malebranche of the Burning Abyss',
    'Burning Abyss - Farfa': 'Farfa, Malebranche of the Burning Abyss',
    'Burning Abyss - Graff': 'Graff, Malebranche of the Burning Abyss',
    'Burning Abyss - Libic': 'Libic, Malebranche of the Burning Abyss',
    'Burning Abyss - Rubic': 'Rubic, Malebranche of the Burning Abyss',
    'Burning Abyss - Scarm': 'Scarm, Malebranche of the Burning Abyss',
    'Burning Abyss - Dante': 'Dante, Traveler of the Burning Abyss',
    'Burning Abyss - Dante, Pilgrim': 'Dante, Pilgrim of the Burning Abyss',
    'Burning Abyss - Virgil': 'Virgil, Rock Star of the Burning Abyss',
    'Burning Abyss - Beatrice': 'Beatrice, Lady of the Eternal',
    'Burning Abyss - Cherubini': 'Cherubini, Ebon Angel of the Burning Abyss',
    'Burning Abyss - Fire Lake': 'Fire Lake of the Burning Abyss',
    'Burning Abyss - Good & Evil': 'Good & Evil in the Burning Abyss',
    'Burning Abyss - Malacoda': 'Malacoda, Netherlord of the Burning Abyss',
    'Burning Abyss - Terminus': 'The Terminus of the Burning Abyss',
    'Burning Abyss - Traveler': 'The Traveler and the Burning Abyss',
    'Curse of the Shadow Prison': 'Curse of the Shadow Prison',
    'El Shaddoll - Anoyatyllis': 'El Shaddoll Anoyatyllis',
    'El Shaddoll - Apkallone': 'El Shaddoll Apkallone',
    'El Shaddoll - Construct': 'El Shaddoll Construct',
    'El Shaddoll - Fusion': 'El Shaddoll Fusion',
    'El Shaddoll - Grysta': 'El Shaddoll Grysta',
    'El Shaddoll - Shekhinaga': 'El Shaddoll Shekhinaga',
    'El Shaddoll - Wendigo': 'El Shaddoll Wendigo',
    'El Shaddoll - Winda': 'El Shaddoll Winda',
    'Hel Shaddoll - Hollow': 'Helshaddoll Hollow',
    'Nael Shaddoll - Ariel': 'Naelshaddoll Ariel',
    'Puru Shaddoll - Aeon': 'Purushaddoll Aeon',
    'Qad Shaddoll - Keios': 'Qadshaddoll Keios',
    'Ree Shaddoll - Wendi': 'Reeshaddoll Wendi',
    'Resh Shaddoll - Incarnation': 'Resh Shaddoll Incarnation',
    'Sinister Shadow Games': 'Sinister Shadow Games',
    'AA-ZEUS - Sky Thunder': 'Divine Arsenal AA-ZEUS - Sky Thunder',
    'Bamboozling Gossip Shadow': 'Number 75 - Bamboozling Gossip Shadow',
    'Big Eye': 'Number 11 - Big Eye',
    'Dugares the Timeless': 'Number 60 - Dugares the Timeless',
    'Hope Harbinger Dragon': 'Number 38 - Hope Harbinger Dragon Titanic Galaxy',
    'Shaddoll - Beast': 'Shaddoll Beast',
    'Shaddoll - Core': 'Shaddoll Core',
    'Shaddoll - Dragon': 'Shaddoll Dragon',
    'Shaddoll - Falco': 'Shaddoll Falco',
    'Shaddoll - Fusion': 'Shaddoll Fusion',
    'Shaddoll - Hedgehog': 'Shaddoll Hedgehog',
    'Shaddoll - Hound': 'Shaddoll Hound',
    'Shaddoll - Schism': 'Shaddoll Schism',
    'Shaddoll - Squamata': 'Shaddoll Squamata',
    'Bagooska': 'Number 41 - Bagooska the Terribly Tired Tapir',
    'Maxx “C”': "Maxx 'C'",
    'Nekroz - Brionac': 'Nekroz of Brionac',
    'Nekroz - Catastor': 'Nekroz of Catastor',
    'Nekroz - Clausolas': 'Nekroz of Clausolas',
    'Nekroz - Cycle': 'Nekroz Cycle',
    'Nekroz - Dance Princess': 'Dance Princess of the Nekroz',
    'Nekroz - Decisive Armor': 'Nekroz of Decisive Armor',
    'Nekroz - Exa': 'Exa, Enforcer of the Nekroz',
    'Nekroz - Great Sorcerer': 'Great Sorcerer of the Nekroz',
    'Nekroz - Gungnir': 'Nekroz of Gungnir',
    'Nekroz - Kaleidoscope': 'Nekroz Kaleidoscope',
    'Nekroz - Mirror': 'Nekroz Mirror',
    'Nekroz - Shurit': 'Shurit, Strategist of the Nekroz',
    'Nekroz - Trishula': 'Nekroz of Trishula',
    'Nekroz - Unicore': 'Nekroz of Unicore',
    'Nekroz - Valkyrus': 'Nekroz of Valkyrus',
    'Silent Honor ARK': 'Number 101 - Silent Honor ARK',
    'Stealth Kragen': 'Number 4 - Stealth Kragen',
    'Comp�tence de Perc�e': 'Breakthrough Skill',
    'D.D Crow': 'D.D. Crow',
    "Dispositif d'�vacuation Obligatoire": 'Compulsory Evacuation Device',
    'Double Tornade': 'Twin Twisters',
    'Enterrement Pr�cipit�': 'Foolish Burial',
    'Explosion Ail�e du Ph�nix': 'Phoenix Wing Wind Blast',
    'Fusion Instantan�e': 'Instant Fusion',
    'Gobelin Parvenu': 'Upstart Goblin',
    'Guide des Enfers': 'Tour Guide From the Underworld',
    'Hommage Torrentiel': 'Torrential Tribute',
    "Livre de l'�clipse": 'Book of Eclipse',
    'Livre de la Lune': 'Book of Moon',
    'Math�maticien': 'Mathematician',
    'Pr�paration des Rites': 'Preparation of Rites',
    'Renaissance du Monstre': 'Monster Reborn',
    'Super Polym�risation': 'Super Polymerization',
    'S�duction des T�n�bres': 'Allure of Darkness',
    'Trou Noir': 'Dark Hole',
    "Typhon d'Espace Mystique": 'Mystical Space Typhoon',
}
